-- products 테이블 (JPA ddl-auto=update로도 생성되며, H2 Console/PostgreSQL 수동 실행용 참고 스크립트)
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    price INTEGER NOT NULL,
    stock INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS product_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    model_code VARCHAR(50) NOT NULL,
    price INTEGER NOT NULL,
    stock INTEGER NOT NULL,
    CONSTRAINT fk_product_models_product FOREIGN KEY (product_id) REFERENCES products(id)
);
